import { useState, useMemo } from "react"
import { useNavigate } from "react-router-dom"
import { Card } from "@/components/ui/Card"
import { Input } from "@/components/ui/Input"
import { EmptyState } from "@/components/ui/EmptyState"
import { Tooltip } from "@/components/ui/Tooltip"
import { ContextMenu, ContextMenuItem, ContextMenuSeparator } from "@/components/ui/ContextMenu"
import { loadLibrary, removeTranscript, toggleFavorite, updateLastViewed } from "@/lib/storage"
import { LibraryState } from "@/data/types"
import {
  Search,
  Trash2,
  Star,
  Clock,
  Calendar,
  BarChart3,
  X,
  ExternalLink,
  Copy,
  FileText,
} from "lucide-react"

type SortKey = "newest" | "oldest" | "alphabetical" | "channel"
type FilterKey = "all" | "favorites" | "manual" | string

export function Library() {
  const [state, setState] = useState<LibraryState>(loadLibrary())
  const [searchQuery, setSearchQuery] = useState("")
  const [sortBy, setSortBy] = useState<SortKey>(() => {
    return (localStorage.getItem("tubescript_library_sort") as SortKey) || "newest"
  })
  const [filterBy, setFilterBy] = useState<FilterKey>(() => {
    return (localStorage.getItem("tubescript_library_filter") as FilterKey) || "all"
  })
  const navigate = useNavigate()

  const transcripts = Object.values(state.transcripts)

  const filteredAndSorted = useMemo(() => {
    let result = [...transcripts]

    if (searchQuery.trim()) {
      const query = searchQuery.toLowerCase()
      result = result.filter(
        (t) =>
          t.title.toLowerCase().includes(query) ||
          t.channel.toLowerCase().includes(query) ||
          t.segments.some((s) => s.text.toLowerCase().includes(query)),
      )
    }

    if (filterBy === "favorites") {
      result = result.filter((t) => t.isFavorite)
    } else if (filterBy === "manual") {
      result = result.filter((t) => !t.isAutoGenerated)
    } else if (filterBy.startsWith("lang-")) {
      result = result.filter((t) => t.language === filterBy.replace("lang-", ""))
    }

    result.sort((a, b) => {
      switch (sortBy) {
        case "newest":
          return new Date(b.addedAt).getTime() - new Date(a.addedAt).getTime()
        case "oldest":
          return new Date(a.addedAt).getTime() - new Date(b.addedAt).getTime()
        case "alphabetical":
          return a.title.localeCompare(b.title)
        case "channel":
          return a.channel.localeCompare(b.channel)
        default:
          return 0
      }
    })

    return result
  }, [transcripts, searchQuery, sortBy, filterBy])

  const handleDelete = (videoId: string) => {
    removeTranscript(videoId)
    setState(loadLibrary())
  }

  const handleFavorite = (videoId: string) => {
    toggleFavorite(videoId)
    setState(loadLibrary())
  }

  const handleCopyURL = (transcript: typeof transcripts[0]) => {
    navigator.clipboard.writeText(`https://www.youtube.com/watch?v=${transcript.videoId}`)
  }

  const availableLanguages = Array.from(
    new Set(transcripts.map((t) => t.language)),
  ).filter(Boolean)

  const activeFilters = useMemo(() => {
    const filters = []
    if (filterBy !== "all") {
      if (filterBy === "favorites") filters.push({ key: "favorites", label: "Favorites" })
      else if (filterBy === "manual") filters.push({ key: "manual", label: "Manual captions" })
      else if (filterBy.startsWith("lang-")) filters.push({ key: filterBy, label: filterBy.replace("lang-", "") })
    }
    return filters
  }, [filterBy])

  const removeFilter = (key: string) => {
    setFilterBy("all")
    localStorage.setItem("tubescript_library_filter", "all")
  }

  const handleSortChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const value = e.target.value as SortKey
    setSortBy(value)
    localStorage.setItem("tubescript_library_sort", value)
  }

  const handleFilterChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const value = e.target.value as FilterKey
    setFilterBy(value)
    localStorage.setItem("tubescript_library_filter", value)
  }

  return (
    <div className="flex-1 h-screen bg-background overflow-y-auto">
      <div className="max-w-6xl mx-auto p-6">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h1 className="text-2xl font-bold text-text mb-2">Library</h1>
            <p className="text-sm text-text-tertiary">
              {transcripts.length} transcript{transcripts.length !== 1 ? "s" : ""} saved
            </p>
          </div>

          <div className="flex gap-2 items-center">
            {/* Active filter chips */}
            {activeFilters.length > 0 && (
              <div className="flex items-center gap-1.5 mr-2">
                {activeFilters.map((filter) => (
                  <div
                    key={filter.key}
                    className="flex items-center gap-1 px-2 py-1 text-xs bg-surface border border-border rounded-md"
                  >
                    <span className="text-text-tertiary">{filter.label}</span>
                    <button
                      onClick={() => removeFilter(filter.key)}
                      className="hover:text-text transition-colors"
                      title="Remove filter"
                    >
                      <X className="w-3 h-3" />
                    </button>
                  </div>
                ))}
              </div>
            )}

            <div className="relative">
              <Input
                placeholder="Search transcripts..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-64"
                icon={<Search className="w-4 h-4" />}
              />
            </div>

            <Tooltip content="Sort by">
              <select
                value={sortBy}
                onChange={handleSortChange}
                className="px-3 py-1.5 text-sm bg-surface border border-border rounded-md text-text focus:outline-none focus:border-text-tertiary transition-colors"
                title="Sort order"
              >
                <option value="newest">Newest first</option>
                <option value="oldest">Oldest first</option>
                <option value="alphabetical">Alphabetical</option>
                <option value="channel">By channel</option>
              </select>
            </Tooltip>

            <Tooltip content="Filter by">
              <select
                value={filterBy}
                onChange={handleFilterChange}
                className="px-3 py-1.5 text-sm bg-surface border border-border rounded-md text-text focus:outline-none focus:border-text-tertiary transition-colors"
                title="Filter"
              >
                <option value="all">All</option>
                <option value="favorites">Favorites</option>
                <option value="manual">Manual captions</option>
                {availableLanguages.map((lang) => (
                  <option key={lang} value={`lang-${lang}`}>
                    {lang}
                  </option>
                ))}
              </select>
            </Tooltip>
          </div>
        </div>

        {filteredAndSorted.length === 0 ? (
          <EmptyState
            title={searchQuery ? "No transcripts matched your search." : "No transcripts yet"}
            description={searchQuery ? "Try a different search term" : "Transcripts you save will appear here"}
          />
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {filteredAndSorted.map((transcript) => (
              <ContextMenu
                key={transcript.videoId}
                trigger={
                  <Card
                    className="p-0 overflow-hidden hover:bg-surface transition-colors"
                    onClick={async () => {
                      await updateLastViewed(transcript.videoId)
                      navigate(`/transcript/${transcript.videoId}`)
                    }}
                  >
                    <div className="flex gap-3 p-4">
                      <div
                        onClick={(e) => {
                          e.stopPropagation()
                          window.open(`https://www.youtube.com/watch?v=${transcript.videoId}`, "_blank")
                        }}
                        title="Open on YouTube"
                      >
                        <img
                          src={transcript.thumbnail}
                          alt={transcript.title}
                          className="w-24 h-14 rounded object-cover bg-surface border border-border flex-shrink-0 cursor-pointer hover:opacity-90 transition-opacity"
                        />
                      </div>
                      <div className="flex-1 min-w-0">
                        <h3 className="font-medium text-text text-sm line-clamp-2 mb-1">
                          {transcript.title}
                        </h3>
                        <p className="text-xs text-text-tertiary mb-2">{transcript.channel}</p>
                        <div className="flex items-center gap-3 text-xs text-text-tertiary">
                          <span className="flex items-center gap-1">
                            <Calendar className="w-3 h-3" />
                            {new Date(transcript.addedAt).toLocaleDateString()}
                          </span>
                          <span className="flex items-center gap-1">
                            <Clock className="w-3 h-3" />
                            {formatDuration(transcript.duration || 0)}
                          </span>
                          <span className={transcript.isAutoGenerated ? "text-blue-400" : ""}>
                            {transcript.isAutoGenerated ? "Auto" : "Manual"}
                          </span>
                        </div>
                      </div>

                      <div className="flex flex-col gap-1 ml-2">
                        <Tooltip content={transcript.isFavorite ? "Remove from favorites" : "Add to favorites"}>
                          <button
                            onClick={(e) => {
                              e.stopPropagation()
                              handleFavorite(transcript.videoId)
                            }}
                            className={`p-1 rounded transition-all duration-300 ${
                              transcript.isFavorite
                                ? "text-white bg-white/10 scale-110"
                                : "text-text-tertiary hover:text-text"
                            }`}
                            title={transcript.isFavorite ? "Remove from favorites" : "Add to favorites"}
                          >
                            <Star className="w-3.5 h-3.5" />
                          </button>
                        </Tooltip>
                        <Tooltip content="Remove from library">
                          <button
                            onClick={(e) => {
                              e.stopPropagation()
                              handleDelete(transcript.videoId)
                            }}
                            className="p-1 rounded text-text-tertiary hover:text-[#ff453a] transition-colors"
                            title="Remove from library"
                          >
                            <Trash2 className="w-3.5 h-3.5" />
                          </button>
                        </Tooltip>
                      </div>
                    </div>
                   </Card>
                 }
                >
                  <ContextMenuItem
                    icon={<Star className="w-4 h-4" />}
                    onClick={() => handleFavorite(transcript.videoId)}
                  >
                    {transcript.isFavorite ? "Remove from" : "Add to"} Favorites
                  </ContextMenuItem>
                  <ContextMenuItem
                    icon={<Copy className="w-4 h-4" />}
                    onClick={() => handleCopyURL(transcript)}
                  >
                    Copy Video URL
                  </ContextMenuItem>
                  <ContextMenuItem
                    icon={<ExternalLink className="w-4 h-4" />}
                    onClick={() => window.open(`https://www.youtube.com/watch?v=${transcript.videoId}`, "_blank")}
                  >
                    Open on YouTube
                  </ContextMenuItem>
                  <ContextMenuSeparator />
                  <ContextMenuItem
                    icon={<FileText className="w-4 h-4" />}
                    onClick={() => navigate(`/transcript/${transcript.videoId}`)}
                  >
                    Open Transcript
                  </ContextMenuItem>
                  <ContextMenuSeparator />
                  <ContextMenuItem
                    icon={<Trash2 className="w-4 h-4" />}
                    destructive
                    onClick={() => handleDelete(transcript.videoId)}
                  >
                    Delete
                  </ContextMenuItem>
                </ContextMenu>
              ))}
            </div>
          )}
        </div>
    </div>
  )
}

function formatDuration(seconds: number): string {
  const m = Math.floor(seconds / 60)
  const s = Math.floor(seconds % 60)
  return `${m}:${s.toString().padStart(2, "0")}`
}
