import type { Chapter, Highlight, KeyMoment, Note, TranscriptData, TranscriptSegment, SavedTranscript } from "./types"

export const MOCK_VIDEO_ID = "tubescript-demo-2024"

export const MOCK_TRANSCRIPT_SEGMENTS: TranscriptSegment[] = [
  { id: "s1", startTime: 0, endTime: 120, text: "Welcome to TubeScript, the modern interactive workspace for YouTube transcripts and video analysis.", confidence: 0.97, speaker: "Alex" },
  { id: "s2", startTime: 120, endTime: 180, text: "I'm going to show you how we can transform any YouTube video into an interactive research environment.", confidence: 0.96, speaker: "Alex" },
  { id: "s3", startTime: 180, endTime: 240, text: "First, let's talk about the transcript extraction process and how we handle different caption formats.", confidence: 0.95, speaker: "Alex" },
  { id: "s4", startTime: 240, endTime: 300, text: "The interesting thing about this system is that the individual components don't actually need to know about each other.", confidence: 0.94, speaker: "Alex" },
  { id: "s5", startTime: 300, endTime: 360, text: "Instead, they communicate through a shared state management system that keeps everything synchronized.", confidence: 0.93, speaker: "Alex" },
  { id: "s6", startTime: 360, endTime: 420, text: "When the video timestamp changes, the transcript automatically updates, highlights persist, and notes remain accessible.", confidence: 0.92, speaker: "Alex" },
  { id: "s7", startTime: 420, endTime: 480, text: "We support search across all your saved transcripts, so you can find specific moments across multiple videos.", confidence: 0.91, speaker: "Alex" },
  { id: "s8", startTime: 480, endTime: 540, text: "You can also highlight important passages, add notes to specific timestamps, and build a personal knowledge base.", confidence: 0.9, speaker: "Alex" },
  { id: "s9", startTime: 540, endTime: 600, text: "The workspace is designed to be colorful and modern, avoiding the generic dashboard aesthetic.", confidence: 0.89, speaker: "Alex" },
  { id: "s10", startTime: 600, endTime: 660, text: "Instead of white backgrounds and black text, we use soft gradients, colorful accent lighting, and subtle glass surfaces.", confidence: 0.88, speaker: "Alex" },
  { id: "s11", startTime: 660, endTime: 720, text: "Chapters are automatically generated and displayed both in the timeline and the intelligence panel.", confidence: 0.87, speaker: "Alex" },
  { id: "s12", startTime: 720, endTime: 780, text: "Each chapter gets its own subtle color, and hovering over a chapter shows the name, start time, and duration.", confidence: 0.86, speaker: "Alex" },
  { id: "s13", startTime: 780, endTime: 840, text: "Key moments are manually tagged by users or AI, and they appear as pink markers along the timeline.", confidence: 0.85, speaker: "Alex" },
  { id: "s14", startTime: 840, endTime: 900, text: "Highlights appear as colored sections in the transcript, and you can select from multiple colors like yellow, blue, pink, and green.", confidence: 0.84, speaker: "Alex" },
  { id: "s15", startTime: 900, endTime: 960, text: "Notes can be attached to any timestamp and appear in the transcript, on the video timeline, and in the right-side intelligence panel.", confidence: 0.83, speaker: "Alex" },
  { id: "s16", startTime: 960, endTime: 1020, text: "A summary is generated covering the main ideas and key points from the entire video.", confidence: 0.82, speaker: "Alex" },
  { id: "s17", startTime: 1020, endTime: 1080, text: "The mini floating player follows you as you scroll through long transcripts, so you always have context.", confidence: 0.81, speaker: "Alex" },
  { id: "s18", startTime: 1080, endTime: 1140, text: "Keyboard shortcuts are built in: Space for play/pause, arrow keys for navigation, Ctrl+F for search.", confidence: 0.8, speaker: "Alex" },
  { id: "s19", startTime: 1140, endTime: 1200, text: "And Esc to close any floating UI. The entire application feels like one connected environment.", confidence: 0.79, speaker: "Alex" },
  { id: "s20", startTime: 1200, endTime: 1260, text: "Thank you for exploring TubeScript. Let's build something amazing together.", confidence: 0.78, speaker: "Alex" },
]

export const MOCK_TRANSCRIPT: TranscriptData = {
  videoId: MOCK_VIDEO_ID,
  title: "The Future of Interactive Video Transcripts",
  channel: "TechTalk Daily",
  thumbnail: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=450&fit=crop",
  language: "en",
  isAutoGenerated: false,
  segments: MOCK_TRANSCRIPT_SEGMENTS,
  channelId: "UC tech talk daily",
  channelThumbnail: "https://ui-avatars.com/api/?name=TechTalk+Daily&background=1a1a2e&color=ff00ff",
  publishedAt: "2024-03-15",
  duration: 1260,
}

export const MOCK_CHAPTERS: Chapter[] = [
  { id: "c1", name: "Introduction", startTime: 0, endTime: 120, color: "from-indigo-500 to-purple-500" },
  { id: "c2", name: "Transcript Extraction", startTime: 120, endTime: 300, color: "from-teal-500 to-emerald-500" },
  { id: "c3", name: "Synchronization", startTime: 300, endTime: 540, color: "from-violet-500 to-pink-500" },
  { id: "c4", name: "Search & Highlights", startTime: 540, endTime: 720, color: "from-orange-500 to-amber-500" },
  { id: "c5", name: "Notes & Analysis", startTime: 720, endTime: 900, color: "from-green-500 to-lime-500" },
  { id: "c6", name: "Conclusion", startTime: 900, endTime: 1260, color: "from-red-500 to-rose-500" },
]

export const MOCK_HIGHLIGHTS: Highlight[] = [
  { id: "h1", transcriptSegmentId: "s4", startTime: 180, endTime: 240, color: "#fbbf24", text: "the individual components don't actually need to know about each other", createdAt: "2024-03-20T10:30:00Z" },
  { id: "h2", transcriptSegmentId: "s8", startTime: 480, endTime: 540, color: "#fbbf24", text: "highlight important passages", createdAt: "2024-03-20T10:35:00Z" },
  { id: "h3", transcriptSegmentId: "s11", startTime: 660, endTime: 720, color: "#fbbf24", text: "Chapters are automatically generated", createdAt: "2024-03-20T10:40:00Z" },
  { id: "h4", transcriptSegmentId: "s14", startTime: 840, endTime: 900, color: "#fbbf24", text: "Highlight colors: yellow, blue, pink, green", createdAt: "2024-03-20T10:45:00Z" },
]

export const MOCK_NOTES: Note[] = [
  { id: "n1", transcriptSegmentId: "s3", startTime: 180, endTime: 240, text: "I want to implement something similar for my project", createdAt: "2024-03-20T10:30:00Z" },
  { id: "n2", transcriptSegmentId: "s7", startTime: 420, endTime: 480, text: "This could be useful for the project I'm building", createdAt: "2024-03-20T10:35:00Z" },
  { id: "n3", transcriptSegmentId: "s12", startTime: 720, endTime: 780, text: "Need to add chapter color hover tooltips", createdAt: "2024-03-20T10:40:00Z" },
]

export const MOCK_KEY_MOMENTS: KeyMoment[] = [
  { id: "m1", timestamp: 180, title: "Modular Design", description: "Components don't need to know about each other", color: "#ec4899" },
  { id: "m2", timestamp: 420, title: "Shared State", description: "Synchronization through shared state", color: "#14b8a6" },
  { id: "m3", timestamp: 600, title: "Colorful Aesthetic", description: "Avoiding generic dashboard look", color: "#8b5cf6" },
  { id: "m4", timestamp: 720, title: "Chapter Markers", description: "Colored chapters in timeline", color: "#f97316" },
  { id: "m5", timestamp: 840, title: "Highlight System", description: "Multiple highlight colors", color: "#ec4899" },
  { id: "m6", timestamp: 960, title: "Floating Player", description: "Follows transcript scroll", color: "#10b981" },
  { id: "m7", timestamp: 1020, title: "Keyboard Shortcuts", description: "Power user navigation", color: "#6366f1" },
  { id: "m8", timestamp: 1140, title: "Conclusion", description: "Thank you for exploring", color: "#f472b6" },
]

export const MOCK_SUMMARY = {
  title: "The Future of Interactive Video Transcripts",
  channel: "TechTalk Daily",
  text: "This video explores how TubeScript transforms YouTube transcripts into an interactive workspace. Key topics include transcript extraction, synchronization across components, search functionality, highlight and note systems, chapter markers, and a colorful modern aesthetic that avoids the generic dashboard look. The application features a three-column layout with video playback, transcript display, and an intelligence panel that provides summaries, key moments, and chapter navigation. Users can highlight transcript sections, attach notes to timestamps, and jump between key moments using keyboard shortcuts or chapter markers. The workspace is designed to feel connected, with every panel synchronized to the current video timestamp.",
}

export const MOCK_LIBRARY_ENTRY: SavedTranscript = {
  ...MOCK_TRANSCRIPT,
  addedAt: "2024-03-20T10:00:00Z",
  lastViewedAt: "2024-03-20T10:00:00Z",
  isFavorite: false,
  highlights: MOCK_HIGHLIGHTS,
  notes: MOCK_NOTES,
}