export interface TranscriptSegment {
  id: string
  startTime: number
  endTime: number
  text: string
  confidence: number
  speaker: string
}

export interface Highlight {
  id: string
  transcriptSegmentId: string
  startTime: number
  endTime: number
  color: string
  text: string
  createdAt: string
}

export interface Note {
  id: string
  transcriptSegmentId: string
  startTime: number
  endTime: number
  text: string
  createdAt: string
}

export interface Chapter {
  id: string
  name: string
  startTime: number
  endTime: number
  color: string
}

export interface KeyMoment {
  id: string
  timestamp: number
  title: string
  description: string
  color: string
}

export interface TranscriptData {
  videoId: string
  title: string
  channel: string
  thumbnail: string
  language: string
  isAutoGenerated: boolean
  segments: TranscriptSegment[]
  channelId?: string
  channelThumbnail?: string
  publishedAt?: string
  duration?: number
}

export interface SavedTranscript extends TranscriptData {
  addedAt: string
  lastViewedAt: string
  isFavorite: boolean
  readingProgress?: {
    segmentId: string
    percentage: number
    lastReadAt: string
    lastPosition: number
  }
  highlights: Highlight[]
  notes: Note[]
}

export interface ChannelData {
  channelId: string
  channelName: string
  channelThumbnail: string
  transcriptIds: string[]
  firstAdded: string
  lastViewed: string
  isFavorite: boolean
}

export interface DownloadData {
  id: string
  videoId: string
  filename: string
  format: "txt" | "md"
  fileSize: number
  exportedAt: string
}

export interface LibraryState {
  transcripts: Record<string, SavedTranscript>
  channels: Record<string, ChannelData>
  favorites: {
    transcripts: string[]
    channels: string[]
  }
  recent: string[]
  downloads: DownloadData[]
  stats: {
    totalTranscripts: number
    totalChannels: number
    totalFavorites: number
    totalDownloads: number
  }
}

export interface TranscriptData {
  videoId: string
  title: string
  channel: string
  thumbnail: string
  language: string
  isAutoGenerated: boolean
  segments: TranscriptSegment[]
  channelId?: string
  channelThumbnail?: string
  publishedAt?: string
  duration?: number
}

export interface SavedTranscript extends TranscriptData {
  addedAt: string
  lastViewedAt: string
  isFavorite: boolean
  readingProgress?: {
    segmentId: string
    percentage: number
    lastReadAt: string
    lastPosition: number
  }
}

export interface ChannelData {
  channelId: string
  channelName: string
  channelThumbnail: string
  transcriptIds: string[]
  firstAdded: string
  lastViewed: string
  isFavorite: boolean
}

export interface DownloadData {
  id: string
  videoId: string
  filename: string
  format: "txt" | "md"
  fileSize: number
  exportedAt: string
}

export interface LibraryState {
  transcripts: Record<string, SavedTranscript>
  channels: Record<string, ChannelData>
  favorites: {
    transcripts: string[]
    channels: string[]
  }
  recent: string[]
  downloads: DownloadData[]
  stats: {
    totalTranscripts: number
    totalChannels: number
    totalFavorites: number
    totalDownloads: number
  }
}