import type { TranscriptData } from "@/data/types"
import {
  TranscriptError,
  createTranscriptError,
  ERROR_CODES,
  isTranscriptError,
} from "@/data/errors"

const PROXY_BASE_URL = "http://localhost:4000"

function buildProxyUrl(path: string, videoId: string, params?: Record<string, string>): string {
  const query = params
    ? "?" + new URLSearchParams(params).toString()
    : ""
  return `${PROXY_BASE_URL}${path}/${videoId}${query}`
}

function decodeHtml(text: string): string {
  const txt = document.createElement("textarea")
  txt.innerHTML = text
  return txt.value
}

async function handleProxyResponse(response: Response): Promise<any> {
  const text = await response.text()

  if (!response.ok) {
    let error: string = ERROR_CODES.UNKNOWN_ERROR
    try {
      const data = JSON.parse(text)
      error = data.error || ERROR_CODES.NETWORK_ERROR
    } catch {
      error = ERROR_CODES.UNKNOWN_ERROR
    }

    if (error === "AGE_RESTRICTED") {
      throw createTranscriptError(ERROR_CODES.AGE_RESTRICTED)
    }
    if (error === "VIDEO_REMOVED" || error === "VIDEO_UNAVAILABLE") {
      throw createTranscriptError(ERROR_CODES.VIDEO_REMOVED)
    }
    if (error === "PRIVATE_VIDEO") {
      throw createTranscriptError(ERROR_CODES.PRIVATE_VIDEO)
    }
    if (error === "CAPTIONS_DISABLED") {
      throw createTranscriptError(ERROR_CODES.CAPTIONS_DISABLED)
    }
    if (error === "TRANSCRIPT_UNAVAILABLE" || error === "CAPTION_UNAVAILABLE") {
      throw createTranscriptError(ERROR_CODES.TRANSCRIPT_UNAVAILABLE)
    }
    throw createTranscriptError(ERROR_CODES.NETWORK_ERROR)
  }

  return JSON.parse(text)
}

export async function fetchTranscript(videoId: string): Promise<TranscriptData> {
  const transcriptUrl = buildProxyUrl("/api/transcript", videoId)

  try {
    const response = await fetch(transcriptUrl)
    const data = await handleProxyResponse(response)

    if (data.error) {
      if (data.error === "AGE_RESTRICTED") {
        throw createTranscriptError(ERROR_CODES.AGE_RESTRICTED)
      }
      if (data.error === "VIDEO_REMOVED" || data.error === "VIDEO_UNAVAILABLE") {
        throw createTranscriptError(ERROR_CODES.VIDEO_REMOVED)
      }
      if (data.error === "PRIVATE_VIDEO") {
        throw createTranscriptError(ERROR_CODES.PRIVATE_VIDEO)
      }
      if (data.error === "CAPTIONS_DISABLED") {
        throw createTranscriptError(ERROR_CODES.CAPTIONS_DISABLED)
      }
      if (data.error === "TRANSCRIPT_UNAVAILABLE" || data.error === "CAPTION_UNAVAILABLE") {
        throw createTranscriptError(ERROR_CODES.TRANSCRIPT_UNAVAILABLE)
      }
      throw createTranscriptError(ERROR_CODES.UNKNOWN_ERROR)
    }

    let segments = data.segments || []
    segments = segments.map((seg: any) => ({
      id: seg.id || `${seg.startTime}-${Math.random().toString(36).slice(2, 8)}`,
      startTime: seg.startTime,
      endTime: seg.endTime,
      text: decodeHtml(seg.text || ""),
      confidence: seg.confidence || 0.9,
    }))

    if (segments.length === 0) {
      throw createTranscriptError(ERROR_CODES.TRANSCRIPT_UNAVAILABLE)
    }

    segments.sort((a: any, b: any) => a.startTime - b.startTime)

    const duration = segments.length > 0
      ? segments[segments.length - 1].endTime
      : 0

    return {
      videoId,
      title: data.title || `YouTube Video (${videoId})`,
      channel: data.channel || "Unknown Channel",
      thumbnail: data.thumbnail || `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`,
      language: data.language || "en",
      isAutoGenerated: data.isAutoGenerated || false,
      segments,
      channelId: data.channelId || "",
      channelThumbnail: data.channelThumbnail || "",
      publishedAt: new Date().toISOString().split("T")[0],
      duration,
    }
  } catch (error) {
    if (isTranscriptError(error)) throw error
    if (error instanceof TypeError) {
      throw createTranscriptError(ERROR_CODES.NETWORK_ERROR, error)
    }
    throw createTranscriptError(ERROR_CODES.UNKNOWN_ERROR)
  }
}

export async function fetchVideoMetadata(videoId: string): Promise<any> {
  const metadataUrl = buildProxyUrl("/api/metadata", videoId)
  const response = await fetch(metadataUrl)

  if (!response.ok) {
    return null
  }

  return await response.json()
}

export function formatSegmentTime(seconds: number): string {
  const h = Math.floor(seconds / 3600)
  const m = Math.floor((seconds % 3600) / 60)
  const s = Math.floor(seconds % 60)

  if (h > 0) {
    return `${h}:${m.toString().padStart(2, "0")}:${s.toString().padStart(2, "0")}`
  }
  return `${m}:${s.toString().padStart(2, "0")}`
}

export { isTranscriptError, TranscriptError }
