const express = require("express")
const cors = require("cors")
const { YoutubeTranscript } = require("youtube-transcript")
const NodeCache = require("node-cache")

const app = express()
const PORT = 4000

// YouTube Data API Key
const YOUTUBE_API_KEY = process.env.YOUTUBE_API_KEY || "AIzaSyCjNc8JjpwuL_9547JAB2xgwQ6BJJmcNzU"

// In-memory cache for channel data (to minimize API quota usage)
const cache = new NodeCache({ stdTTL: 3600, checkperiod: 600 }) // 1 hour TTL

app.use(cors())
app.use(express.json({ limit: "50mb" }))
app.use(express.urlencoded({ limit: "50mb", extended: true }))

const YOUTUBE_BASE = "https://www.youtube.com"
const USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

const fetchYouTube = require("node-fetch")

app.get("/api/transcript/:videoId", async (req, res) => {
  const { videoId } = req.params

  try {
    const result = await fetchTranscript(videoId)
    res.json(result)
  } catch (error) {
    console.error("Transcript error:", error?.message || error)
    res.status(500).json({ error: "UNKNOWN_ERROR" })
  }
})

app.get("/api/metadata/:videoId", async (req, res) => {
  const { videoId } = req.params
  try {
    const oembedUrl = `${YOUTUBE_BASE}/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`
    const response = await fetchYouTube(oembedUrl, {
      headers: {
        "User-Agent": USER_AGENT,
        Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.5",
      },
    })

    if (!response.ok) {
      return res.status(404).json({ error: "VIDEO_UNAVAILABLE" })
    }

    const data = await response.json()
    res.json({
      title: data.title || `YouTube Video (${videoId})`,
      author: data.author_name || "Unknown Channel",
      author_name: data.author_name || "Unknown Channel",
      thumbnail_url: data.thumbnail_url || `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`,
    })
  } catch (error) {
    res.json({
      title: `YouTube Video (${videoId})`,
      author: "Unknown Channel",
      author_name: "Unknown Channel",
      thumbnail_url: `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`,
    })
  }
})

async function fetchTranscript(videoId) {
  try {
    const transcript = await YoutubeTranscript.fetchTranscript(videoId, {
      lang: "en",
    })

    if (!transcript || transcript.length === 0) {
      return { error: "TRANSCRIPT_UNAVAILABLE" }
    }

    const metadata = await fetchMetadataWithDetails(videoId)

    const segments = []
    const seenTexts = new Set()

    for (const seg of transcript) {
      const text = seg.text.trim()
      if (!text) continue

      const startTime = seg.offset / 1000
      const endTime = (seg.offset + (seg.duration || 4000)) / 1000

      const key = `${startTime}-${text}`
      if (seenTexts.has(key)) continue
      seenTexts.add(key)

      segments.push({
        id: `${startTime}-${Math.random().toString(36).slice(2, 8)}`,
        startTime,
        endTime,
        text: text,
        confidence: seg.confidence || 0.9,
      })
    }

    if (segments.length === 0) {
      return { error: "TRANSCRIPT_UNAVAILABLE" }
    }

    segments.sort((a, b) => a.startTime - b.startTime)

    const isAutoGenerated = transcript[0]?.lang === "en" && segments.length > 10 || false

    return {
      videoId,
      title: metadata.title || `YouTube Video (${videoId})`,
      channel: metadata.author || metadata.author_name || "Unknown Channel",
      channelThumbnail: metadata.channel_thumbnail || `https://ui-avatars.com/api/?name=${encodeURIComponent(metadata.author_name || metadata.author || "X")}&background=1a1a1a&color=ffffff&size=128`,
      thumbnail: metadata.thumbnail_url,
      language: "en",
      isAutoGenerated: isAutoGenerated || false,
      segments,
      channelId: metadata.channel_id || "",
    }
  } catch (error) {
    console.error("Fetch transcript error:", error?.message || error)
    if (error?.message?.includes("Could not get video")) {
      return { error: "VIDEO_UNAVAILABLE" }
    }
    if (error?.message?.includes("No transcript") || error?.message?.includes("transcript")) {
      return { error: "TRANSCRIPT_UNAVAILABLE" }
    }
    if (error?.message?.includes("age") || error?.message?.includes("AGE_RESTRICTED")) {
      return { error: "AGE_RESTRICTED" }
    }
    return { error: "UNKNOWN_ERROR" }
  }
}

async function fetchMetadataWithDetails(videoId) {
  const oembedUrl = `${YOUTUBE_BASE}/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`
  let oembedData = null

  try {
    const response = await fetchYouTube(oembedUrl, {
      headers: {
        "User-Agent": USER_AGENT,
        Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.5",
      },
    })

    if (response.ok) {
      oembedData = await response.json()
    }
  } catch (error) {
    // continue
  }

  let channelThumbnail = null
  let channelId = null
  let channelName = oembedData?.author_name || "Unknown Channel"

  try {
    const watchUrl = `${YOUTUBE_BASE}/watch?v=${videoId}`
    const watchResponse = await fetchYouTube(watchUrl, {
      headers: {
        "User-Agent": USER_AGENT,
        Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.9",
      },
    })

    if (watchResponse.ok) {
      const html = await watchResponse.text()

      // Extract channel ID
      const channelIdMatch = html.match(/"channelId":"(UC[^"]+)"/)
      if (channelIdMatch) {
        channelId = channelIdMatch[1]
      }
    }
  } catch (error) {
    // continue
  }

  // Try fetching channel thumbnail via YouTube Data API v3 (preferred method)
  if (channelId) {
    const cachedThumbnail = cache.get(`channel_thumb_${channelId}`)
    if (cachedThumbnail) {
      channelThumbnail = cachedThumbnail
    } else {
      channelThumbnail = await fetchChannelThumbnailFromAPI(channelId)
      if (channelThumbnail) {
        cache.set(`channel_thumb_${channelId}`, channelThumbnail)
      }
    }
  }

  // Fallback to HTML scraping if API didn't return a thumbnail
  if (!channelThumbnail && channelId) {
    try {
      const watchUrl = `${YOUTUBE_BASE}/watch?v=${videoId}`
      const watchResponse = await fetchYouTube(watchUrl, {
        headers: {
          "User-Agent": USER_AGENT,
          Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
          "Accept-Language": "en-US,en;q=0.9",
        },
      })

      if (watchResponse.ok) {
        const html = await watchResponse.text()
        const avatarMatch = html.match(/"channelAvatar":\{"thumbnails":\[{"url":"([^"]+)"/)
        if (avatarMatch) {
          channelThumbnail = avatarMatch[1].replace(/\\\//g, "/")
        }
      }
    } catch (error) {
      // continue
    }
  }

  return {
    title: oembedData?.title || `YouTube Video (${videoId})`,
    author_name: channelName || oembedData?.author_name || "Unknown Channel",
    author: channelName || oembedData?.author_name || "Unknown Channel",
    author_url: oembedData?.author_url || (channelId ? `https://www.youtube.com/channel/${channelId}` : null),
    thumbnail_url: oembedData?.thumbnail_url || `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`,
    channel_thumbnail: channelThumbnail,
    channel_id: channelId || oembedData?.author_url?.replace("https://www.youtube.com/channel/", "") || null,
  }
}

// Fetch channel thumbnail via YouTube Data API v3
async function fetchChannelThumbnailFromAPI(channelId) {
  try {
    const apiUrl = `https://www.googleapis.com/youtube/v3/channels?part=snippet&id=${channelId}&key=${YOUTUBE_API_KEY}`
    const response = await fetchYouTube(apiUrl, {
      headers: {
        Accept: "application/json",
      },
    })

    if (response.ok) {
      const data = await response.json()
      if (data.items && data.items.length > 0) {
        const thumbs = data.items[0].snippet.thumbnails
        // Prefer high quality, then medium, then default
        return thumbs.high?.url || thumbs.medium?.url || thumbs.default?.url || null
      }
    }
    return null
  } catch (error) {
    console.error("YouTube Data API error:", error?.message || error)
    return null
  }
}

async function fetchMetadata(videoId) {
  try {
    const oembedUrl = `${YOUTUBE_BASE}/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`
    const response = await fetchYouTube(oembedUrl, {
      headers: {
        "User-Agent": USER_AGENT,
        Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.5",
      },
    })

    if (!response.ok) {
      return {
        title: `YouTube Video (${videoId})`,
        author: "Unknown Channel",
        thumbnail_url: `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`,
      }
    }

    const data = await response.json()
    return {
      title: data.title || `YouTube Video (${videoId})`,
      author: data.author_name || "Unknown Channel",
      thumbnail_url: data.thumbnail_url || `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`,
    }
  } catch (error) {
    return {
      title: `YouTube Video (${videoId})`,
      author: "Unknown Channel",
      thumbnail_url: `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`,
    }
  }
}

app.listen(PORT, () => {
  console.log(`TubeScript proxy server running on http://localhost:${PORT}`)
})
